name: raman_ai_backend
channels:
  - conda-forge
  - defaults
  - pytorch
dependencies:
  - python=3.11
  - django>=4.2
  - djangorestframework
  - django-cors-headers
  - mysqlclient
  - pandas
  - numpy
  - scipy
  - scikit-learn
  - openpyxl
  - cryptography
  - pytorch
  - pip  # 必须添加这一行！
  - pip:
    - djangorestframework-simplejwt